version: "3.8"
services:
  maven-tests:
    image: maven:3.9.6-eclipse-temurin-8
    working_dir: /app
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: /var/run/docker.sock
      TESTCONTAINERS_HOST_OVERRIDE: host.docker.internal
      SPRING_PROFILES_ACTIVE: test
    command: mvn -B -e verify
